# Generated by Django 4.2 on 2023-06-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='last_sync_at',
            field=models.DateTimeField(null=True),
        ),
    ]
