# Generated by Django 4.2 on 2023-07-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='chunking_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
