# Generated by Django 4.2 on 2023-06-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='sync_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
