# Generated by Django 4.2 on 2023-08-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_template_chunking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='account_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
