# Generated by Django 4.2 on 2023-06-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integration_sync_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.CharField(blank=True, max_length=200, null=True)),
                ('obj_type', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
